name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Print Secret
        run: echo "Access Token: ${{ secrets.ACCESS_TOKEN }}"
      
      - name: Build and deploy
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          yarn install
          yarn build
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git checkout -B gh-pages
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push --force origin gh-pages
